export { default as App } from '../containers/App'
export { default as Header } from './Header'
export { default as Counter } from './Counter'
export { default as Slider } from './Slider'
export { default as Home } from './Home'